#!/bin/sh

echo "Job starting: executing run_PLV_Bernat for channel pair "$1"."

/usr/local/bin/matlab -nosplash -nodisplay -r "cd /home/bp/Bernat_NMDAR_antagonists/, run ../startup, matlabpool, load('channels.mat'), pairs = nchoosek(1:3,2); run_PLV_Bernat(1000, location_channels{pairs($1,1)}, location_channels{pairs($1,2)}), end, quit"
